### PR TITLE
Implemented User Account Creation and Login

### LINKED ISSUE #11: Implement account creation
Implement account creation to lock survey creation to registered accounts.

### PR DESCRIPTION
**Pull request by douglytle**
I have implemented user account creation and login features, as per Issue #11. This includes various templates, a new controller, and a new persistence entity, the "user". I have not yet implemented related features such as surveys belonging to users, but will update the issues list with these related facets of user account functionality.

### CODE REVIEW

**Comment by Sgt-Roukoz** [comment]
Looks good so far, one small thing you could do to show login however, is hide the create survey link if you are not logged in (but show account creation/login), then show the create survey link if you are logged in (hiding account creation/login, replacing it with a user profile or something). We should have some indicator in each relevant page of you being logged in currently (maybe in the top right of the page have a "Logged in as: X" tag)

You should add a Back to Homepage link in the login page.

**Comment by douglytle** [comment]
I have implemented all of your requested changes. The user login status is now stored using an HttpSession object. The links displayed to the user on the home page will change depending on if they are logged in, and there is text on screen which displays the current account or informs the user they are not logged in. I have also added a log out feature, and added more links for navigation between pages as requested.

**Comment by Sgt-Roukoz** [comment]
Everything looks good so far, but I would recommend adding tests for the new model additions.

**Comment by douglytle** [comment]
Unit Tests for the new additions have been implemented

**Review by Sgt-Roukoz — APPROVED** [review]
User Account addition looks good, and tests pass. Good job

**Pull request merged**
